// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjpqgrossrunhmhpcuup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqcHFncm9zc3J1bmhtaHBjdXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjg5MzYsImV4cCI6MjA2NDgwNDkzNn0.0y1ifSqb3WqU2TLDP-p4UhbrOoUMtQwPhRF4NmdQRWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);